# Generated by Django 2.2.3 on 2019-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookPrice',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
